In [5]:
import numpy as np


a = np.array([[12, 13, 14], 
              [2, 3, 1]])
print(a.ndim)  
print(a.shape) 
print(a.size)  

2
(2, 3)
6


In [6]:
print(a.T)

[[12  2]
 [13  3]
 [14  1]]


In [7]:
print(a[0:1]) 
print(a[0:1,2]) 
print(a[:,1])

[[12 13 14]]
[14]
[13  3]


In [10]:
print(np.zeros((3, 4)))
print(np.ones((2, 3), dtype=np.int16))
print(np.random.rand(2,3))
print(np.eye(2))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[0.61803987 0.97096922 0.29979953]
 [0.56768299 0.04852624 0.25431863]]
[[1. 0.]
 [0. 1.]]


In [11]:
print(a.reshape(3, 2))

[[12 13]
 [14  2]
 [ 3  1]]


TypeError: 'numpy.flatiter' object is not callable

In [14]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
print(np.append(a, b, axis=0))

[[1 2 3]
 [2 3 4]]


In [15]:
print(np.append(a, b, axis=1))

[[1 2 3 2 3 4]]


In [16]:
print(np.linalg.inv([[3, 1], [1, 2]]))

[[ 0.4 -0.2]
 [-0.2  0.6]]


In [17]:
print(a + b)

[[3 5 7]]


In [22]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 3], [4, 5]])
print(np.matmul(a, b))

[[10 13]
 [22 29]]


In [25]:
print(np.arange(0, 2, 0.3))
print(a.sum())
print(a.sum(axis=0)) 
print(a.sum(axis=1))  
print(a.mean())
print(np.sqrt(a)) 

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
10
[4 6]
[3 7]
2.5
[[1.         1.41421356]
 [1.73205081 2.        ]]
